### ISSUE TITLE
Add shortcut to copy, paste text.

### ISSUE THREAD

**Issue by ahmadraniri1994** [k-stha/msterm#1]
Hello, It's kind of petty question but how to add shortcut (e.g copy/paste text) ? I have very limitted knowledge about python.

I found a piece of code, but don't know how to implement them : 

```
def _key_press_event(self, widget, event):
		# Vte terminal key press event,
		# allow Copy/Paste in the terminal

		keyval = event.keyval
		keyval_name = Gdk.keyval_name(keyval)
		state = event.state

		ctrl = (state & Gdk.ModifierType.CONTROL_MASK)
		shift = (state & Gdk.ModifierType.SHIFT_MASK)

		if ctrl and shift and keyval_name == 'C':
			# Ctrl+Shit+C - copy
			self.copy_clipboard_format(Vte.Format.TEXT)

		if ctrl and shift and keyval_name == 'V':
			# Ctrl+Shit+V - paste
			self.paste_clipboard()
```

Thanks.

**Comment by k-stha** [comment]
Sorry for a very late response. I have been exploring some ways of implementing the feature you are asking for, but, have been unsuccessful so far. Also, I do the following for copy-paste inside msterm:

1. I use tmux, configured to handle clipboard with wl-clipboard (since I use Sway Window Manager), for copy and paste.
2. I use Middle-mouse-click clipboard functionality to paste and select text to copy.

If you find way(s) to implement the copy-paste feature inside msterm, I would be happy to implement it.

**Comment by ahmadraniri1994** [comment]
Thanks.
